### ISSUE TITLE
Watch error event crashes application even with .on('error', cb)

### ISSUE THREAD

**Issue by MottyMAnyVision** [silas/node-consul#106]
Getting 'request timed out' error (some problem with my service communication) and I do have an on error event handler but it seems as though one of the events is not caught and crashes my app, the following is the error from my logs, the first error is from my service logger meaning I caught it and the second one is the error that crashes my app (I think it originates from a double error event in papi that your code uses):
*** the method I gave to watch is consul.kv.get

2020-11-08T16:56:21.730Z ERROR ... Watch failed on key ... Error: consul: kv.get: request timed out (33000ms)
    at create (/home/node/subjects-service/node_modules/papi/lib/errors.js:14:5)
    at Object.timeout [as Timeout] (/home/node/subjects-service/node_modules/papi/lib/errors.js:62:15)
    at ClientRequest.<anonymous> (/home/node/subjects-service/node_modules/papi/lib/client.js:532:20)
    at ClientRequest.emit (events.js:321:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at Timeout.<anonymous> (/home/node/subjects-service/node_modules/papi/lib/client.js:520:11)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
events.js:298
      throw er; // Unhandled 'error' event
      ^
Error: request timed out (33000ms)
    at create (/home/node/subjects-service/node_modules/papi/lib/errors.js:14:5)
    at Object.timeout [as Timeout] (/home/node/subjects-service/node_modules/papi/lib/errors.js:62:15)
    at ClientRequest.<anonymous> (/home/node/subjects-service/node_modules/papi/lib/client.js:532:20)
    at ClientRequest.emit (events.js:321:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at Timeout.<anonymous> (/home/node/subjects-service/node_modules/papi/lib/client.js:520:11)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Emitted 'error' event on Watch instance at:
    at Watch._err (/home/node/subjects-service/node_modules/consul/lib/watch.js:138:8)
    at /home/node/subjects-service/node_modules/consul/lib/watch.js:162:21
    at next (/home/node/subjects-service/node_modules/papi/lib/client.js:305:32)
    at Consul.body (/home/node/subjects-service/node_modules/consul/lib/utils.js:18:27)
    at next (/home/node/subjects-service/node_modules/papi/lib/client.js:311:10)
    at ClientRequest.<anonymous> (/home/node/subjects-service/node_modules/papi/lib/client.js:505:5)
    at ClientRequest.emit (events.js:321:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at ClientRequest.<anonymous> (/home/node/subjects-service/node_modules/papi/lib/client.js:534:9)
    at ClientRequest.emit (events.js:321:20)
    [... lines matching original stack trace ...]
    at processTimers (internal/timers.js:492:7) {
  isPapi: true,
  isTimeout: true
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
...

**Comment by silas** [comment]
Can you post the version of node, node-consul, and papi you're using, example:

``` sh
$ node --version
v15.0.1
$ npm ls | grep -E '(papi@|consul@)'
consul@0.39.0
├── papi@0.29.1
```

And a small snippet that shows how to create the watch and attach the event handler, example:

``` js
const watch = consul.watch({
  method: consul.kv.get,
  options: { key: 'somekey' },
});

watch.on('error', function(err) {
  console.log('error:', err);
});
```

**Comment by MottyMAnyVision** [comment]
From my package lock:

"consul": {
      "version": "0.34.1",
      "resolved": "https://registry.npmjs.org/consul/-/consul-0.34.1.tgz",
      "integrity": "sha1-sABjitmdsDj7uY5QjDLXWL9ZiWg=",
      "requires": {
        "papi": "^0.29.0"
      }
    },



I'm using node 12

Code snippet:

async watchKeys(keys = [], onChangeCB = () => {}) {
    await Promise.map(keys, async key => {
      if (!this.watchesMap[key]) {
        this.watchesMap[key] = this.consul.watch({ method: this.consul.kv.get, options: { key, recurse: true } })
      }
      this.watchesMap[key]
        .on('change', async data => {
          const value = convertResult(data)
          logger.debug(`Settings key ${ key } value has changed: ${ JSON.stringify(value) }`)
          await this.cache.set(this._getCacheKey(key), value)
          onChangeCB(value)
        })
        .on('error', err => logger.error(err, `watch failed on key: ${ key }`))
    })
  }

**Comment by silas** [comment]
I wasn't able to produce this using those versions.

Couple of questions/thoughts:
 * you're not populating `watchesMap` anywhere else correct?
 * it looks like you're using domains, which makes this even more confusing (domains should automatically handle event errors if you don't)
 * what logger package+version are you using, is it possible it is re-emitting that error?

**Comment by MottyMAnyVision** [comment]
* All work with consul.watch and `watchesMap` is done only in this function
* can you please explain what do you mean by domains?
* I am using pino 5.17.0 for logger, I'm doing this code with the logger for all my errors I never had such an issue
* I can't reproduce this error in a small script, in order to reproduce I need to somehow recreate multiple 'request timed out' errors

is there any other info I can supply?

**Comment by silas** [comment]
You can see `ClientRequest.EventEmitter.emit (domain.js:482:12)` in your stack trace, which is a reference to Node.js domains: https://nodejs.org/api/domain.html, which was specifically built to deal with unhandled exceptions.

It is probably used by some framework you use.

Probably won't change anything, but might be worth updating to the latest version of consul.

Not sure when I'm going to be able to dig into this again, I spent a couple of hours trying to reproduce it and digging through code (it's easy for me to trigger that timeout, as it's an option, but I could never get it to not be handled by the on error handler).

**Comment by MottyMAnyVision** [comment]
Sorry for the inconvenience, found a usage of consul in one of our packages that is missing an on error handler
Again very sorry
