### ISSUE TITLE
Won't initialize with default params

### ISSUE THREAD

**Issue by brettlaforge** [silas/node-consul#11]
node-consul won't initialize with default params

```
var consul = require('consul')();
```

```
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Expecting a function in instanceof check, but got http://127.0.0.1:8500/v1
    at Consul.Client (/vagrant/web/node_modules/consul/node_modules/papi/lib/client.js:44:36)
    at new Consul (/vagrant/web/node_modules/consul/lib/consul.js:43:15)
    at Consul (/vagrant/web/node_modules/consul/lib/consul.js:30:12)
    at Object.<anonymous> (/vagrant/web/index.js:7:9)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:32)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:41)
```

The papi library is now checking the baseUrl to make sure its an instance of url.Url. node-consul is creating a baseUrl string. Which fails on the test.

**Comment by brettlaforge** [comment]
Nevermind.. had a really old version of node
