### ISSUE TITLE
TypeError: consul_1.default is not a constructor

### ISSUE THREAD

**Issue by Douglas0n** [silas/node-consul#124]
My code:
```javascript
import Consul from 'consul';

const consul = new Consul();
await consul.kv.get('hello');
```
Library version: **"consul": "^0.40.0"**

Full error:
```
[Nest] 206220  - 06/08/2022, 10:15:51 AM   ERROR [ExceptionsHandler] consul_1.default is not a constructor
TypeError: consul_1.default is not a constructor
    at AppService.getConsulValues (/home/douglas0n/Projects/APPS/devops-sandbox-service/src/app.service.ts:15:20)
    at AppController.getConsulValues (/home/douglas0n/Projects/APPS/devops-sandbox-service/src/app.controller.ts:14:34)
    at /home/douglas0n/Projects/APPS/devops-sandbox-service/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at InterceptorsConsumer.intercept (/home/douglas0n/Projects/APPS/devops-sandbox-service/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:11:20)
    at /home/douglas0n/Projects/APPS/devops-sandbox-service/node_modules/@nestjs/core/router/router-execution-context.js:46:60
    at /home/douglas0n/Projects/APPS/devops-sandbox-service/node_modules/@nestjs/core/router/router-proxy.js:9:23
    at Layer.handle [as handle_request] (/home/douglas0n/Projects/APPS/devops-sandbox-service/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/douglas0n/Projects/APPS/devops-sandbox-service/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/douglas0n/Projects/APPS/devops-sandbox-service/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/douglas0n/Projects/APPS/devops-sandbox-service/node_modules/express/lib/router/layer.js:95:5)

```

**Comment by silas** [comment]
Version 0.40.0 used a callback interface by default and didn't use `new`.

Version `1.0.0` which is now released works with this syntax.
