### ISSUE TITLE
Returning stale (cached?) results?

### ISSUE THREAD

**Issue by jodawill** [silas/node-consul#84]
Hi!

My apologies if the mistake is on my end. Here's my problem. I'm trying to run a test that writes a key to console, then retrieves the value to verify that it worked. But when I use node-consul, I often get back stale results.

Here's some code that represents my problem:

```
#!/usr/bin/env node

require('dotenv').config();
const sleep = require('sleep').sleep;

const getConsulClient = async () => {
  let options = {
    host: process.env.CONSUL_HOST,
    port: 8500,
    secure: true,
    defaults: {
      token: process.env.CONSUL_ACL
    },
    promisify: true
  };

  return require('consul')(options);
};

const getConsulConfig = async (key) => {
  const client = await getConsulClient();
  let result;
  try {
    result = await client.kv.get(key);
    return (result).Value;
  } catch(e) {
    console.log({e});
    return '';
  }
};

const setConsulConfig = async (key, value) => {
  const client = await getConsulClient();
  if (client.kv.set(key, value.toString())) {
  } else {
    throw `Error writing ${key} to Consul`;
  }
};

const deleteConfig = async (key) => {
  const client = await getConsulClient();
  if (client.kv.del(key)) {
  } else {
    throw `Error deleting ${key} from Consul`;
  }
};

const runTest = async (key) => {
  for (let i = 0; i < 30; i++) {
    await setConsulConfig(key, `foo-${i}`);
    const result = await getConsulConfig(key);

    console.log(`${i} - read`, {result}, result === `foo-${i}` ? 'good' : 'bad');
    sleep(1);
  }
  await deleteConfig(key);
};

runTest('footest-2019');
```

And here's an example of the output I get. (It's different every time.)

```
{ e:
   TypeError: Cannot read property 'Value' of undefined
       at getConsulConfig (/Users/jodawill/GitHub/docker-redis-cluster/example.js:25:21)
       at process._tickCallback (internal/process/next_tick.js:68:7) }
0 - read { result: '' } bad
1 - read { result: 'foo-0' } bad
2 - read { result: 'foo-1' } bad
3 - read { result: 'foo-2' } bad
4 - read { result: 'foo-3' } bad
5 - read { result: 'foo-4' } bad
6 - read { result: 'foo-5' } bad
7 - read { result: 'foo-6' } bad
8 - read { result: 'foo-7' } bad
9 - read { result: 'foo-9' } good
10 - read { result: 'foo-9' } bad
11 - read { result: 'foo-10' } bad
12 - read { result: 'foo-11' } bad
13 - read { result: 'foo-12' } bad
14 - read { result: 'foo-14' } good
15 - read { result: 'foo-14' } bad
16 - read { result: 'foo-15' } bad
17 - read { result: 'foo-16' } bad
18 - read { result: 'foo-17' } bad
19 - read { result: 'foo-18' } bad
20 - read { result: 'foo-19' } bad
21 - read { result: 'foo-21' } good
22 - read { result: 'foo-22' } good
23 - read { result: 'foo-22' } bad
24 - read { result: 'foo-23' } bad
25 - read { result: 'foo-25' } good
26 - read { result: 'foo-25' } bad
27 - read { result: 'foo-26' } bad
28 - read { result: 'foo-27' } bad
29 - read { result: 'foo-28' } bad
```

I'm running Consul 1.4.2. This seems to be a problem with node-consul itself because I don't encounter this problem when I use Postman.

Any idea of what's going on here? Am I doing something wrong, or is it a bug?

Thanks,

Josh

**Comment by silas** [comment]
You need to `await` the `set` and `del` calls, example `if (await client.kv.set(key, value.toString())) {` and `if (await client.kv.del(key)) {`.

**Comment by jodawill** [comment]
That works. Thanks!
